### ISSUE TITLE
Possible clarifications to instructions

### ISSUE THREAD

**Issue by jay-aye-see-kay** [wmdebrito/googleOTP-to-andOTP#2]
First; thanks a lot for publishing this, it saved me a bunch of time migrating to andOTP

I'm not super familiar with the protobuf ecosystem so I got a little stuck on what I needed to install, then I got this error. I'm not sure why it couldn't find that module, I'd already installed the protobuf package with `pip3`, but I fixed it by executing all the commands in a venv (I suspect this is related to using a mac with system python 2.7).

```
Traceback (most recent call last):
  File "toAndOTP.py", line 3, in <module>
    from GAuthPayload_pb2 import GAuthPayload
  File "/Users/jack/temp/googleOTP-to-andOTP/GAuthPayload_pb2.py", line 5, in <module>
    from google.protobuf import descriptor as _descriptor
ModuleNotFoundError: No module named 'google'
```

My suggested changes to the install steps would be to step 7, something like this
```sh
# set up a virtual env
python 3 -m venv venv
source venv/bin/activate

# install python protobuf package (you need an OS install of protobuf too, as mentioned in the pre-requirements)
pip install protobuf
python toAndOTP.py <input file> <output file>.json
```

Hopefully the above helps someone else

**Comment by wmdebrito** [comment]
Updated https://github.com/wmdebrito/googleOTP-to-andOTP/blob/master/README.md
Thank you
